### ISSUE TITLE
How long are the feeds cached?

### ISSUE THREAD

**Issue by ethus3h** [ciderpunx/twitrssme#13]
It's been all day and my feed hasn't updated....

**Comment by ciderpunx** [comment]
24 hours

**Comment by ethus3h** [comment]
Cool, thanks! :)

**Comment by ciderpunx** [comment]
Bytemark have offered to host the project, which means that I am going to start experimenting with caching for less time. So currently 12 hours, but it will probably continue to drop in the next days
