### ISSUE TITLE
could fetch some twitter user's  rss

### ISSUE THREAD

**Issue by limhio** [ciderpunx/twitrssme#16]
user id:songma,virushuo,etc.

**Comment by ciderpunx** [comment]
Sorry this can't be fixed. twitrss.me works by scraping users public twitter profiles, but the accounts you mention have protected their tweets, which means they have no tweets in their public profiles, and hence that there is nothing for twitrss to scrape. 

```
@songma's Tweets are protected.
@virushuo's Tweets are protected.
```
