### ISSUE TITLE
pb with a japanese account

### ISSUE THREAD

**Issue by jcmag** [ciderpunx/twitrssme#17]
Using twitrssme with this account: @asahi, doesn't work (https://twitrss.me/twitter_user_to_rss/?user=asahi, only one item displayed).
Is it a problem related to the japanese characters?

**Comment by ciderpunx** [comment]
I /think/ its resolved now; it was pretty slow to load so there may be some unicode weirdness going on that has disappeared now.

**Comment by ciderpunx** [comment]
Closing, as believe solved
