### ISSUE TITLE
pubDate must be an RFC-822 date-time

### ISSUE THREAD

**Issue by ao2** [ciderpunx/twitrssme#18]
Hi, ``twitter_user_to_rss.pl`` does not output valid RSS feeds, http://www.feedvalidator.org gives me this error:

```
pubDate must be an RFC-822 date-time: mar, 01 dic 2015 12:19:41 +0100
```
Here is an explanation: http://www.feedvalidator.org/docs/error/InvalidRFC2822Date.html

BTW, make sure to check out also Tweeper (https://git.ao2.it/tweeper.git/)  which tries to solve the same problem but —IMHO— uses a little cleaner approach using XSL, and supports also Instagram, Facebook public pages and some other sites.

If you want to share efforts for this Walled-Garden-to-RSS problem feel free to get in touch.

**Comment by ciderpunx** [comment]
Hah, that's weird, it is ok for @ciderpunx, except for a couple of warnings.
http://www.feedvalidator.org/check.cgi?url=http://twitrss.me/twitter_user_to_rss/?user=ciderpunx

Have you got a test case that gives an invalid feed?

Tweeper seems like a good project happy to link it on twitrss.me if you like.

**Comment by ao2** [comment]
Apparently the issue is about ``strftime`` and the user locale.

I was running ``twitter_user_to_rss.pl``from the command line and I have ``LC_TIME="it_IT.utf8"``, and the ``%a`` and ``%b`` format specifiers are locale-dependent. if I run the script with ``LC_TIME=POSIX`` the pubDate becomes an actual RFC-822 date-time.

Please let me know if you actually give tweeper a try.

JFYI not all the the dependencies of  ``twitter_user_to_rss.pl`` are packaged for Debian, I had to get ``LWP-Protocol-Net-Curl`` and ``perl-Net-Curl`` from CPAN in order to be able to run it.

Ciao ciao,
   Antonio
