### ISSUE TITLE
Remove ellipsis from after urls

### ISSUE THREAD

**Issue by MitchellMcKenna** [ciderpunx/twitrssme#2]
Urls currently all have an ellipsis (...) after them. The ellipsis comes out as html entities `&#xA0;&#x2026;` in the RSS. I believe you can remove them by doing something like this on line 88:

`$body=~s/&#xA0;&#x2026;//g;`

**Comment by t3chguy** [comment]
+1

**Comment by ciderpunx** [comment]
Thanks for reporting. Can't reproduce now, so I guess it must be fixed.
