### ISSUE TITLE
Internal Server Error on one feed

### ISSUE THREAD

**Issue by mhoran** [ciderpunx/twitrssme#22]
A few weeks ago, http://www.twitrss.me/twitter_user_to_rss/?user=adkap started returning a 500 error when fetching. When I look at Adam's timeline, I see a RT that has been ["withheld"](https://twitter.com/MrNobre/status/754144048529625088) due to copyright claims. Could this be causing TwitRSS.me to choke?

**Comment by ciderpunx** [comment]
Yes, that will be it. TwitRSS.me works by screenscraping the page, so it will break when the page doesn't have a feed on it. Sorry about that.

**Comment by mhoran** [comment]
Is there any way to skip over these erroneous Tweets, instead of returning a 500 error?
