### ISSUE TITLE
Feeds not reachable

### ISSUE THREAD

**Issue by marco-IT** [ciderpunx/twitrssme#23]
Hi.

My Twitter feeds seems to be unreachble more often in the last days. I use the TwitRSS feeds as source in  FeedPress and got "unreachable" warnings first at August 20 and also yesterday and today.
It's for the Twitter accounts **MH_personally**, **MH_WI**, **MH_magazin**, **marco_IT_WI**, **servus_IT_WI** and **DJ_Xcite_WI**.

Current tests of [**MH_personally with https**](https://twitrss.me/twitter_user_to_rss/?user=mh_personally&replies=on) results in "ERR_TIMED_OUT", but [**without secure http**](http://twitrss.me/twitter_user_to_rss/?user=mh_personally&replies=on) it seems to works - I got [this](https://drive.google.com/open?id=0Bxw_8s6Y25icYWEweVY0YUlpd00) back.
FeedPress also said, it's a valid feed, but fetching it results again in an error: "The service is not available. Please try again later."

Please check this.

Kind regards,
Michael.

**Comment by reddit-is-fun** [comment]
Currently I can't access the homepage https://twitrss.me/

**Comment by marco-IT** [comment]
Now it's accessible (at the moment...)

**Comment by ciderpunx** [comment]
Having a problem with hundreds of connections per second from thousands of clients. Working on mitigation, but might take a while.

**Comment by ciderpunx** [comment]
I think this is now resolved (by switching from pound to haproxy) please re-open if not.
