### ISSUE TITLE
Remove "Twitter Search" prefix

### ISSUE THREAD

**Issue by 07416** [ciderpunx/twitrssme#26]
`Twitter Search` prefix is added at the start of every feed - can this be removed?

**Comment by ciderpunx** [comment]
This is to maintain compatibility with the original v1 API so will probably stay

**Comment by ciderpunx** [comment]
I'll leave the issue open in case you're not alone in finding this annoying though.

**Comment by bobpage** [comment]
You're not alone; I've manually edited the title for a few hundred feeds.
