### ISSUE TITLE
RSS feed not updating timely

### ISSUE THREAD

**Issue by Ev1dentFir3** [ciderpunx/twitrssme#41]
How often does it poll a twitter feed? I'm using the RSS feed for another program reading tweets from an account that posts about every 15 minutes. I was parsing your RSS feed every minute to look for updates but at least 30 minutes went buy with no updates, and so it missed tweets as a result.

**Comment by Ev1dentFir3** [comment]
just to be clear I didn't expect it to update every minute, that was just my check rate. I'm just curious how often it does because I waited 30 minutes for an update and didn't see one so just asking. thanks!

**Comment by ciderpunx** [comment]
Its cached for about 45 minutes.

**Comment by Ev1dentFir3** [comment]
ok thanks for the info
