### ISSUE TITLE
Are e-mail notifications out of the question?

### ISSUE THREAD

**Issue by mzso** [ciderpunx/twitrssme#42]
Hi!
I was wondering if there's any possibility of adding support for e-mail notifications.

Since the feature is not present already, I'm wondering if it has drawbacks. Do e-mails require more website traffic than feeds updating every hour or so? I wouldn't think so, but don't know...

**Comment by KNTRO** [comment]
@mzso Hi there!

Have not you tried [Blogtrottr](https://blogtrottr.com/) to receive feeds' updates right in your email account? :wink:

**Comment by mzso** [comment]
[**@KNTRO**](https://github.com/KNTRO) commented on [2018. febr. 4. 06:56 CET](https://github.com/ciderpunx/twitrssme/issues/42#issuecomment-362883178 "2018-02-04T05:56:25Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) Hi there!
> 
> Have not you tried [Blogtrottr](https://blogtrottr.com/) to receive feeds' updates right in your email account? <g-emoji class="g-emoji" alias="wink" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f609.png" ios-version="6.0">😉</g-emoji>

I've been using it. Though getting them directly without advertisements would have been nice.

**Comment by ciderpunx** [comment]
I'm afraid not on the email updates front - twitrss is just an rss tool. 

Like KNTRO suggests blogtrottr or an IFTT recipe like https://ifttt.com/applets/147561p-rss-feed-to-email  may work for you.
