### ISSUE TITLE
as of today, right now, twitrss.me is not working at all

### ISSUE THREAD

**Issue by left1000** [ciderpunx/twitrssme#52]
if I go to the website I'm told:
ERR: Can’t screenscrape Twitter
if I try to update my feeds in rssowl I'm told 404.

this url doesn't do anything useful in my browser or my rss reader http://twitrss.me/twitter_user_to_rss/?user=ciderpunx

as of yesterday it was working perfectly :(
I really hope this comes back! I loved hiding twitter purely inside my rss reader.

**Comment by Yarn** [comment]
It looks like twitter changed their default behavior to serve the mobile site for some user agents (observed with python requests). This may be the cause of the issue. Spoofing a desktop user agent restored old behavior.

---

adding 
```pl
$browser->agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36")
```
below line 25 of
https://github.com/ciderpunx/twitrssme/tree/e688c6da040aac31cebf0decee668da7c5f05d01/fcgi/twitter_user_to_rss.pl

would likely fix the issue if someone wants to try it

**Comment by sdt** [comment]
I've had a quick play and the fix from @Yarn above works for me

**Comment by ciderpunx** [comment]
Thanks folks, in particular @Yam! That fix seems to resolve the issue. I've flushed the cache so you'll probably notice slow responses for the next while as the server catches up with the request backlog.

**Comment by sdt** [comment]
Thanks @Yarn and @ciderpunx !
