### ISSUE TITLE
CoreBot on discord

### ISSUE THREAD

**Issue by ZerooCool** [ciderpunx/twitrssme#57]
This link work good and add the content to discord.
.getrss http://twitrss.me/twitter_user_to_rss/?user=Visionduweb

This link doesn't work, CoreBot don't add the content to discord.
.getrss http://twitrss.me/twitter_user_to_rss/?user=progressistes75

**Comment by ciderpunx** [comment]
TwitRSS isn't discord or 'CoreBot'. 

If you can get some details about /why/ 'CoreBot' doesn't like the feed, feel free to re-open the ticket.

Otherwise, I am assuming all is functioning as expected...
