### ISSUE TITLE
Favicon is empty

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [ciderpunx/twitrssme#73]
Please check

http://twitrss.me/favicon.ico

The file is there but empty.

**Comment by ciderpunx** [comment]
This was a performance trick; many browsers request a favicon, but I don't have one I wanted to use, so an empty file is super quick to deliver!

**Comment by noMICROSOFTbuhtz** [comment]
I see your point but this behaviour does not affect performance anymore today. In the past it does.

Favicon or not won't have an effect on the loading and rendering performance in Chrome and Firefox.

Because of your (against the standard) case my newsreader need to implement a special check for this.

I would recommand to fit to the standard.
