### ISSUE TITLE
Mobile Twitter RSS doesn't work anymore

### ISSUE THREAD

**Issue by crockpoot** [ciderpunx/twitrssme#86]
A few months ago, the API changed and I was recommended to use "/mobile_twitter_to_rss" as a temporary solution. I took a great liking to this method because of how lightweight it was and it worked well for me until today. The original one "/twitter_user_to_rss"works perfectly fine but at this point, I really only want to use the mobile one.

**Comment by crockpoot** [comment]
Started having this problem again.

**Comment by ciderpunx** [comment]
Is this the case if you run locally. My guess is that TwitRSS is over capacity (again.)
