### ISSUE TITLE
Service down - Internal Server Error

### ISSUE THREAD

**Issue by ZerooCool** [ciderpunx/twitrssme#90]
http://twitrss.me/twitter_search_to_rss/?term=visionduweb

**Comment by chovy** [comment]
I'm seeing this too. Rather frustrating. You can use a proxy rotator service so twitter doesn't ban your api: https://www.scraperapi.com/?fp_ref=anthony24 -- this one is $29/mo for 250k request. but you should cache searches so you donj't burn through your limit.

**Comment by ciderpunx** [comment]
Just over capacity on the server side by the looks of it, fixed now.

**Comment by ZerooCool** [comment]
Hmm, I don't know much about proxy.
Have you planned documentation to explain all this?

Can i use free proxy ?

**Comment by ciderpunx** [comment]
At present there is no need to use a proxy, and TwitRSS does not use a proxy. So there isn't be any need for documentation because there's nothing to explain.
