### ISSUE TITLE
Twitter update

### ISSUE THREAD

**Issue by crockpoot** [ciderpunx/twitrssme#92]
Twitter updated something and broke the app. Please fix before my backlog gets to nightmarish again.

**Comment by creideiki** [comment]
Probably has something to do with the old web interface shutting down yesterday, which made the GoodTwitter browser extension stop working: https://twitter.com/ZusorOW/status/1258885451055800320

**Comment by ciderpunx** [comment]
Thanks for letting me know folks, the mobile_twitter_to_rss.pl version looks to be working for now, I'll redirect traffic n the site there for now - prob not going to be able to look at this properly today.

**Comment by votemp** [comment]
Possibly relevant fix: https://github.com/twintproject/twint/pull/774/commits/1ad346b38e9574544011e96cada69b7091016eb1

**Comment by dperelman** [comment]
The fix @votemp linked worked for me. I made a small PR that adds that header which works for me running locally.

**Comment by crockpoot** [comment]
Thanks for the speedy fix!

**Comment by pozirk** [comment]
Is it broken again?.. ;(

**Comment by dperelman** [comment]
Yeah, looks like Twitter closed that loophole pretty quickly. [twintproject/twint](https://github.com/twintproject/twint) appears to be broken as well. Either that or I can't figure out how to use it.

**Comment by kalaklanar** [comment]
mobile_twitter_to_rss.pl is still working on my install

**Comment by ciderpunx** [comment]
Ah, that didn't last long. I've reverted to using mobile_twitter_to_rss.pl  on the web service. I'm currently getting "Too many requests" errors, but that could just be while caches warm up. Will see,,,

**Comment by dperelman** [comment]
As `twint` is having the same issue, keeping an eye on twintproject/twint#756 and twintproject/twint#782 may help... but so far they have nothing.

**Comment by crockpoot** [comment]
Dang, I was hoping this wasn't the case when my RSS spat out only a dozen new entries :^\

**Comment by dperelman** [comment]
... and it suddenly started working again for me. Probably temporary...

**Comment by crockpoot** [comment]
Weird stuff lol

**Comment by pozirk** [comment]
Not working for me.

**Comment by rootless4real** [comment]
I was able to get twint to scrape, but not the latest trss.  Has anyone else gotten it working?

**Comment by zedeus** [comment]
The solution is to rewrite part of twitrss from scratch, or use Nitter's rss feeds instead. Right before the UI change I rewrote Nitter to use the new public JSON API, but it's a massive change https://github.com/zedeus/nitter/pull/169

**Comment by crockpoot** [comment]
> The solution is to rewrite part of twitrss from scratch, or use Nitter's rss feeds instead. Right before the UI change I rewrote Nitter to use the new public JSON API, but it's a massive change [zedeus/nitter#169](https://github.com/zedeus/nitter/pull/169)

Hope this works; the backlog.... is getting dire.....

**Comment by zedeus** [comment]
https://nitter.net serves tens of thousands of requests every day, ~5k RSS feeds daily, it works.

**Comment by crockpoot** [comment]
Any updates?

**Comment by jkuj6** [comment]
Seems nitter is the way to go. However id still like to know if this will be fixed for twitrss, @ciderpunx ?

**Comment by takemeover** [comment]
I didn't realize this was part of the same issue whoops

**Comment by ciderpunx** [comment]
Hey @jkuj6 Like zedeus said it probably means a complete rewrite. I'm /really/ short of time at present, so  no time soon; unless someone has capacity to take that on. 

FWIW the mobile version, though it doesn't work on twitrss.me works to the extent that twitter doesn't rate limit you - so you can run an instance of your own.

**Comment by bmomjian** [comment]
I don't even have a Twitter account to log in, so I switched to using a free account at https://fetchrss.com/ to get a feed.  It says the free account only has a 24-hour update rate.

**Comment by zedeus** [comment]
You can use Nitter without a Twitter account, it has a 10 minute update rate (you can self-host and change it).

**Comment by bmomjian** [comment]
Thanks @zedeus, I got it working and it seems fine.  I was able to remove all the caching stuff I needed when twitrssme wasn't working, so that is a win.

**Comment by crockpoot** [comment]
I'd use nitter too but I really need the original URLs for media, unfortunately :(

**Comment by bmomjian** [comment]
I am already processing the RSS file with Perl, so I just changed nitter.net to twitter.com in the URLs,

**Comment by crockpoot** [comment]
Any updates?

**Comment by crockpoot** [comment]
Renew certificates, please

**Comment by crockpoot** [comment]
Is there ever getting fixed? It's been way too long.

**Comment by leonstafford** [comment]
> It's been way too long.

@crockpoot - as a maintainer of other open source projects, there's no such thing as "way too long". 

The source code is all here, so if it's critical for you / worth something to fix and you can't make the changes (or in this case, maybe rewrite from scratch) yourself, you may be able to hire someone to do that for you. Whether you choose to share that fix back to the project and they accept it is another matter.

**Comment by crockpoot** [comment]
> > It's been way too long.
> 
> @crockpoot - as a maintainer of other open source projects, there's no such thing as "way too long".
> 
> The source code is all here, so if it's critical for you / worth something to fix and you can't make the changes (or in this case, maybe rewrite from scratch) yourself, you may be able to hire someone to do that for you. Whether you choose to share that fix back to the project and they accept it is another matter.

You're right, I think of that
