### ISSUE TITLE
Searching Twitter User = Page of html codes?

### ISSUE THREAD

**Issue by darkarth00** [ciderpunx/twitrssme#94]
Hello,

if I'm trying to find a twitter user and click on fetch rss I get a page which is just full of html codes since yesterday or so...

https://s12.directupload.net/images/200603/swqw6bn7.png

**Comment by ciderpunx** [comment]
This is RSS that you are seeing. Maye you changed browser or something like that?

**Comment by darkarth00** [comment]
I trieed different browsers with standard settings and without add-ons at this doesn't help.

If I use chrome-based Browsers I get this code and if I use firefox he wants me to save a file. Type: "application/rss+xmt"

This isn't what it should be right?

Normally I use your site to convert twitter to rss links. So normally it works fine. A few days ago I got the error message "ERR: Can’t screenscrape Twitter" when I wanted to find a twitter user.

Then I came here to see if someone already reported and I found the "Twitter update #92" Thread. So I thought it will be working soon again. Then came votemp's fix. And after you responsed to it, I got this code.

So to me it doesn't look like the failure is on my side. I don't know.

By the way: If I want to search for terms I get this:

"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."

**Comment by ciderpunx** [comment]
> If I use chrome-based Browsers I get this code and if I use firefox he wants me to save a file. 
> Type: "application/rss+xmt"
> This isn't what it should be right?

Firefox has been doing that for a while, they got rid of native RSS support in FF 64 -- cf. https://www.eweek.com/enterprise-apps/firefox-64-boosts-tab-management-drops-rss

I think Chrome has done it that way for some time. See eg. https://support.google.com/chrome/thread/2173477?hl=en

> By the way: If I want to search for terms I get this:

> "Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your 
> request.

I've fixed the search bug, but looks like the web service is getting blocked right now for too many requests. I'd leave it an hour or two and try then.
